/* GAPIClientLib.cpp
   Generated by gSOAP 2.7.10 from GoogleSearch.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "GAPIC.cpp"
#include "GAPIClient.cpp"

/* End of GAPIClientLib.cpp */
