// generated 2007/11/29 21:04:06 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.12.1 and gtkmm 2.12.0
//
// Please modify the corresponding derived classes in ./src/importDialog.hh and./src/importDialog.cc

#ifndef _IMPORTDIALOG_GLADE_HH
#  define _IMPORTDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/entry.h>
#include <gtkmm/label.h>
#include <gtkmm/comboboxtext.h>
#include <gtkmm/table.h>

class importDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Button * importButton;
        class Gtk::Entry * titleEntry;
        class Gtk::Label * titleLabel;
        class Gtk::ComboBoxText * labelNameCombobox;
        class Gtk::Entry * locationEntry;
        class Gtk::Table * docTable;
        
        importDialog_glade();
        
        ~importDialog_glade();
private:
        virtual void on_importButton_clicked() = 0;
        virtual void on_locationEntry_changed() = 0;
};
#endif
