// generated 2008/12/27 19:39:02 SGT by fabrice@rexor.dyndns.org.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.14.5 and gtkmm 2.14.3
//
// Please modify the corresponding derived classes in ./src/prefsWindow.hh and./src/prefsWindow.cc

#ifndef _PREFSWINDOW_GLADE_HH
#  define _PREFSWINDOW_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/button.h>
#include <gtkmm/treeview.h>
#include <gtkmm/comboboxtext.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/label.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/colorbutton.h>
#include <gtkmm/table.h>
#include <gtkmm/notebook.h>

class prefsWindow_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Button * prefsCancelbutton;
        class Gtk::Button * prefsOkbutton;
        class Gtk::TreeView * directoriesTreeview;
        class Gtk::Button * addDirectoryButton;
        class Gtk::Button * removeDirectoryButton;
        class Gtk::TreeView * patternsTreeview;
        class Gtk::ComboBoxText * patternsCombobox;
        class Gtk::Button * addPatternButton;
        class Gtk::Button * removePatternButton;
        class Gtk::Button * resetPatternsButton;
        class Gtk::TreeView * labelsTreeview;
        class Gtk::Button * addLabelButton;
        class Gtk::Button * removeLabelButton;
        class Gtk::RadioButton * directConnectionRadiobutton;
        class Gtk::RadioButton * proxyRadiobutton;
        class Gtk::Entry * proxyAddressEntry;
        class Gtk::SpinButton * proxyPortSpinbutton;
        class Gtk::ComboBoxText * proxyTypeCombobox;
        class Gtk::Label * apiKeyLabel;
        class Gtk::Entry * apiKeyEntry;
        class Gtk::CheckButton * enableCompletionCheckbutton;
        class Gtk::ColorButton * newResultsColorbutton;
        class Gtk::CheckButton * ignoreRobotsCheckbutton;
        class Gtk::Label * robotsLabels;
        class Gtk::Table * generalTable;
        class Gtk::Notebook * prefsNotebook;
        
        prefsWindow_glade();
        
        ~prefsWindow_glade();
private:
        virtual void on_prefsCancelbutton_clicked() = 0;
        virtual void on_prefsOkbutton_clicked() = 0;
        virtual void on_addDirectoryButton_clicked() = 0;
        virtual void on_removeDirectoryButton_clicked() = 0;
        virtual void on_patternsCombobox_changed() = 0;
        virtual void on_addPatternButton_clicked() = 0;
        virtual void on_removePatternButton_clicked() = 0;
        virtual void on_resetPatternsButton_clicked() = 0;
        virtual void on_addLabelButton_clicked() = 0;
        virtual void on_removeLabelButton_clicked() = 0;
        virtual void on_directConnectionRadiobutton_toggled() = 0;
        virtual bool on_prefsWindow_delete_event(GdkEventAny *ev) = 0;
};
#endif
