// generated 2007/1/9 20:01:15 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.10.4 and gtkmm 2.10.5
//
// Please modify the corresponding derived classes in ./src/statisticsDialog.hh and./src/statisticsDialog.cc

#ifndef _STATISTICSDIALOG_GLADE_HH
#  define _STATISTICSDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/treeview.h>
#include <gtkmm/scrolledwindow.h>

class statisticsDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::TreeView * statisticsTreeview;
        class Gtk::ScrolledWindow * statisticsScrolledwindow;
        
        statisticsDialog_glade();
        
        ~statisticsDialog_glade();
};
#endif
